## To get started with security, check out the documentation:
## http://symfony.com/doc/current/book/security.html
#security:
#
#    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
#    providers:
#        in_memory:
#            memory: ~
#
#    firewalls:
#        # disables authentication for assets and the profiler, adapt it according to your needs
#        dev:
#            pattern: ^/(_(profiler|wdt)|css|images|js)/
#            security: false
#
#        main:
#            anonymous: ~
#            # activate different ways to authenticate
#
#            # http_basic: ~
#            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate
#
#            # form_login: ~
#            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
             #connexion par nom d'utilisateur
#            id: fos_user.user_provider.username
             #connexion par email ou nom d'utilisateur
             id: fos_user.user_provider.username_email 

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern:  ^/$
            security: false
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider
                login_path:     /
                use_forward:    false
                default_target_path: /accueil
#                always_use_default_target_path: true #Toujours redirig sur la page par défaut ici accueil
                check_path:     /login_check
                failure_handler: ccdn_user_security.component.authentication.handler.login_failure_handler
                remember_me: true
            logout:       true
            logout:
                handlers: [logout_listener]
                path:   /logout
                target: /   #url où sera redirigé l'utilisateur après sa déconnexion
                invalidate_session: false
            anonymous:    true
            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
#                always_remember_me: true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY } #Permettre l'inscription
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY} #Sécuriser toutes les pages
