adresse_index:
    path:     /
    defaults: { _controller: "BaseMainBundle:Adresse:index" }
    methods:  GET

adresse_show:
    path:     /{id}/show
    defaults: { _controller: "BaseMainBundle:Adresse:show" }
    methods:  GET

adresse_new:
    path:     /new
    defaults: { _controller: "BaseMainBundle:Adresse:new" }
    methods:  [GET, POST]

adresse_edit:
    path:     /{id}/edit
    defaults: { _controller: "BaseMainBundle:Adresse:edit" }
    methods:  [GET, POST]

adresse_delete:
    path:     /{id}/delete
    defaults: { _controller: "BaseMainBundle:Adresse:delete" }
    methods:  DELETE
