alerte_index:
    path:     /
    defaults: { _controller: "BaseMainBundle:Alerte:index" }
    methods:  GET

alerte_show:
    path:     /{id}/show
    defaults: { _controller: "BaseMainBundle:Alerte:show" }
    methods:  GET

alerte_new:
    path:     /new
    defaults: { _controller: "BaseMainBundle:Alerte:new" }
    methods:  [GET, POST]

alerte_edit:
    path:     /{id}/edit
    defaults: { _controller: "BaseMainBundle:Alerte:edit" }
    methods:  [GET, POST]

alerte_delete:
    path:     /{id}/delete
    defaults: { _controller: "BaseMainBundle:Alerte:delete" }
    methods:  DELETE
