<?php

namespace Base\MainBundle\Entity;

/**
 * ConnexionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConnexionRepository extends \Doctrine\ORM\EntityRepository
{
}
