<?php

namespace Base\MainBundle\Entity;

/**
 * PersonneSocieteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonneSocieteRepository extends \Doctrine\ORM\EntityRepository
{
}
